apiVersion: apps/v1
kind: Deployment
metadata:
  name: neko-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neko-dev
  template:
    metadata:
      labels:
        app: neko-dev
    spec:
      containers:
      - name: neko-dev
        image: gcr.io/cogent-task-430211-d5/neko:latest
        ports:
        - name: http
          containerPort: 8080
        - name: udp-55000
          containerPort: 55000
        - name: udp-55001
          containerPort: 55001
        - name: udp-55002
          containerPort: 55002
        - name: udp-55003
          containerPort: 55003
        - name: udp-55004
          containerPort: 55004
        - name: udp-55005
          containerPort: 55005
        - name: udp-55006
          containerPort: 55006
        - name: udp-55007
          containerPort: 55007
        - name: udp-55008
          containerPort: 55008
        - name: udp-55009
          containerPort: 55009
        env:
        - name: NEKO_SCREEN
          value: "1920x1080@60"
        - name: NEKO_EPR
          value: "55000-55009"
        - name: NEKO_ICELITE
          value: "true"
        - name: NEKO_MAX_FPS
          value: "25"
        - name: NEKO_NAT1TO1
          value: "UDP_EXTERNAL_IP"
        - name: NEKO_IMPLICIT_CONTROL
          value: "true"
