apiVersion: v1
kind: Service
metadata:
  name: neko-dev-tcp-service
spec:
  type: LoadBalancer
  selector:
    app: neko-dev
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8080